DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
  ORDERID VARCHAR(100) NOT NULL,
  PRODUCTID VARCHAR(2000) NOT NULL,
  productName VARCHAR(2000) NOT NULL,
  productDescription VARCHAR(2000) NOT NULL,
  customerId VARCHAR(2000) NOT NULL,
  firstName VARCHAR(2000) NOT NULL,
  lastName VARCHAR(2000) NOT NULL
);